### ISSUE TITLE
different xarray versions in datacube dc_1.0.yaml and DQtools affects pickles

### ISSUE THREAD

**Issue by NPounder** [Assimila/DQTools#5]
conda environments dc_1.0.yaml and dqtools_0.1.yaml  Have different versions of xarray. This prevents DQtools running in dqtools_0.1 from writing to a datacube server running in dc_1.0

DQtools will pickle an xarray before passing to the datacube that will unpickle the xarray. This must be done using the same version of xarray or it will fail. This will not be a problem if both DQtools and datacube are using the same environment or if DQtools is using a different version but is not required to write to the datacube

https://github.com/Assimila/DQTools/blob/9ef2c8c36c4bd5dafff8a32ea7c8829b6f7af10c/env/dqtools_0.1.yml#L45

**Comment by purplecat7** [comment]
win/dqtools_0.4  and  linux/dqtools_0.3  both use  xarray-0.12.1  as does datacube/dc_1.3
